services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_port_connectivity
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - scraping_network

  python_scraper:
    build:
      context: .
      dockerfile: ./Dockerfile.python
    container_name: python_scraper
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./scrapers:/app/scrapers
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./jobs:/app/jobs
    networks:
      - scraping_network
    restart: on-failure
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1

  go_processor:
    build:
      context: .
      dockerfile: ./Dockerfile.go
    container_name: go_processor
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - scraping_network
    environment:
      - RABBITMQ_HOST=rabbitmq
    command: ["/app/processors/main"]

networks:
  scraping_network:
    driver: bridge